import React from 'react'
import { getPosts, getPostDetails } from '../../services'
import { PostDetail, Categories, PostWidget, Author, Comments, CommentsForm, Loader } from '../../components'
import Head from 'next/head'
import { useRouter } from 'next/router'

const PostDetails = ({ data }) => {
    const router = useRouter();

    if (router.isFallback) {
        return <Loader />
    }
    
    return (
        <>
            <Head>
                <title>{data.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container mx-auto px-10 mb-8">
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
                    <div className="col-span-1 lg:col-span-8">
                        <PostDetail post={data} />
                        <Author author={data.author} />
                        <CommentsForm slug={data.slug} />
                        <Comments slug={data.slug} />
                    </div>
                    <div className="col-span-1 lg:col-span-4">
                        <div className="relative lg:sticky top-8">
                            <PostWidget slug={data.slug} categories={data.categories.map((cate) => cate.slug)} />
                            <Categories />
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default PostDetails

//fecth api
export async function getStaticProps({ params }) {
    const data = await getPostDetails(params.slug)

    return {
        props: {
            data
        }
    }
}

export async function getStaticPaths() {
    const posts = await getPosts()

    return {
        paths: posts.map(({ node: { slug } }) => ({ params: { slug } })),
        fallback: true,
    }
}